### PR TITLE
Add 'add_callback' and 'del_callback' methods.

### PR DESCRIPTION
**Pull request by sphh**
I needed a method to add a callback from inside a class (see example in `README.md`).

At the same time I took the liberty to remove the `keys()` calls to dictionary, because they are not required (any more) (see https://docs.python.org/3/library/stdtypes.html#dict-views)

### CODE REVIEW

**Comment by AsbjornOlling** [comment]
Hm.. This may be an API improvement, but I'm not sure it actually solves the problem you say it does.

You can absolutely add event callbacks inside classes with the current `on_event` functions.
Like so:

```python
class Mopidy:

    def __init__(self):
        self.m = MopidyAPI()
        m.on_event('volume_changed')(self.print_volume)
        m.on_event('track_playback_started')(self.print_newtracks)

    def print_volume(self, event):
        print(f"Volume changed to: {event.volume}")

    def print_newtracks(self, event):
        print(f"Started playing track: {event.track.name}")
```

However, this is probably not very intuitive to people who aren't familiar with how python decorators work.

The way I see it, the `add_callback` and `delete_callback` method are:
- A prettier method for adding callbacks programatically (without needing to call the return value of the decorator function)
- A far more ergonomic way to remove callbacks (without messing with the internal `_event_callbacks` dict).

But I don't think it is anything specifically related to classes.

**Comment by sphh** [comment]
Yes, you are absolutely right, it has nothing to do with classes. That was just my starting point …

That one is certainly very elegant:
```python3
     m.on_event('volume_changed')(self.print_volume)
```
but I would have never figured it out myself without your help! It would be ok, if it is documented somewhere …

In any way, there should still be a way to remove a callback ‘the easy way’.

**Comment by AsbjornOlling** [comment]
There was some errors in the `del_callback` method (function body referred to `method`, but parameter was called `f`). I also refactored `on_event` to use the new `add_callback` function.

But it has been merged now. Thanks for your work!

**Comment by sphh** [comment]
Re `method` and `f`: You are absolutely right. My oversight, so sorry!

Re `on_event`: I thought about that, but didn't want to fiddle with decorators! :wink:

Thanks for improving the documentation. It is now much clearer!

**Pull request merged**
